### ISSUE TITLE
Opening "filling with spout" recipe for Chocolate Pie crashes game

### ISSUE THREAD

**Issue by lgowen22** [Anxxitty/farmers-delight-JEI-plugin#1] opened 2023-02-05 23:19 UTC
Self-explanatory, it happens without this mod (since it doesn't add any create recipes) but this didn't seem like a bad place to post an issue about it.

**Comment by Anxxitty** [comment] 2023-02-07 22:21
I came across this crash too while playing with create and farmers delight. It comes from the fact that farmers delight uses the tag c:chocolates instead of c:chocolate in the recipe for the chocolate pie, though I don't know if this is a bug from farmers delight or if it works under REI but not JEI, and then it would be a crash caused by my mod. I will find out soon and fix the issue if it only happens with JEI. Though if it happens with both REI and JEI then please report the issue to the fabric port of Farmers Delight, I wont fix a general issue of farmers delight in this mod. But if you want a quick and easy fix that you can apply right now, you can create a datapack in which you add create:chocolate (check the name of the fluid I'm not sure if it's chocolate or melted_chocolate or something like that) to the c:chocolates tag, and the issue will be fixed. If you don't know how to make datapacks I'll send it to you in waiting of a real fix.

**Comment by Anxxitty** [comment] 2023-09-10 16:36
issue closed because the bug has been fixed by Farmer's Delight devs

**Closed as completed** 2023-09-10 16:35 UTC
